M48
; DRILL file {KiCad 9.0.7} date 2026-03-12T18:11:07+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-12T18:11:07+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X100.185Y-55.16
X105.035Y-55.16
T2
X96.919Y-52.624
X96.946Y-99.623
X108.261Y-52.627
X108.312Y-99.623
T3
X99.885Y-52.13
X105.335Y-52.13
M30
